Add support for sanitizing favorites.
dichro/ephemera pull request #2
Opened 2018-08-02 20:37 UTC by cgeisser

2018-08-07 04:04 UTC, dichro requested changes
Sorry for the delay, and thank you for attacking favs!

2018-08-07 04:04 UTC, dichro commented on twitter/cmd/archive.go
> +			if _, err := (TweetType{}).Key().Get(db, id); err == nil {
Rather than instantiating TweetType and FavType inline in various places, you could just make globals and reuse them. Put something like this somewhere (timeline.go?):

var (
  Tweets TweetType
  Likes FavType
)

...and then just reference them where necessary?

2018-08-10 15:20 UTC, cgeisser commented on twitter/cmd/archive.go
> +			if _, err := (TweetType{}).Key().Get(db, id); err == nil {
Good plan, done.

2018-08-16 17:34 UTC, cgeisser commented
Fixed.

2018-08-17 02:05 UTC, dichro approved these changes

2018-08-17 02:05 UTC, merged

2018-08-17 02:05 UTC, dichro commented
Thank you!